In [10]:
import torch
local_rank=0
device = torch.device("cuda", local_rank)
ckpt_path="results/garden/ckpts/ckpt_29999_rank0.pt"
ckpt = torch.load(ckpt_path, map_location=device)["splats"]
test = torch.load(ckpt_path, map_location=device)

In [14]:
test

{'step': 29999,
 'splats': OrderedDict([('means',
               tensor([[-1.4666e-01, -1.2953e+00,  5.0196e-01],
                       [-9.9463e-03, -1.5171e-03,  3.1582e-01],
                       [-1.2193e+00,  2.1297e+00, -3.7651e-02],
                       ...,
                       [-2.2891e+00, -1.7026e+00,  1.4600e+00],
                       [-1.6654e-01, -3.6670e+00,  7.1649e-01],
                       [-4.9093e-01,  1.7446e+00,  1.4491e-01]], device='cuda:0')),
              ('opacities',
               tensor([-3.7513,  0.0904, 10.1199,  ...,  3.0447,  8.6965, -2.1282],
                      device='cuda:0')),
              ('quats',
               tensor([[ 9.2810e-01,  6.4304e-01,  6.1049e-01,  1.0423e+00],
                       [ 2.9011e-01,  7.0701e-01,  6.2319e-01,  5.4454e-01],
                       [ 1.2141e+00,  4.1889e-01,  9.7812e-01,  3.9718e-04],
                       ...,
                       [ 5.0405e-01,  9.4745e-01,  2.6264e-01, -2.9845e-01],
     